In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/two-sigma-connect-rental-listing-inquiries/images_sample.zip
/kaggle/input/competitions/two-sigma-connect-rental-listing-inquiries/Kaggle-renthop.torrent
/kaggle/input/competitions/two-sigma-connect-rental-listing-inquiries/sample_submission.csv.zip
/kaggle/input/competitions/two-sigma-connect-rental-listing-inquiries/test.json.zip
/kaggle/input/competitions/two-sigma-connect-rental-listing-inquiries/train.json.zip

In [2]:
#ライブラリの読み込み
import pandas as pd
import numpy as np

# 可視化
import matplotlib.pyplot as plt
import seaborn as sns

# モデル
import lightgbm as lgb
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import log_loss

# 保存
import pickle

# テキスト処理
from sklearn.feature_extraction.text import TfidfVectorizer

# 便利系
from tqdm import tqdm
import gc

In [3]:
#データの読み込み
train = pd.read_json("/kaggle/input/competitions/two-sigma-connect-rental-listing-inquiries/train.json.zip")
test = pd.read_json("/kaggle/input/competitions/two-sigma-connect-rental-listing-inquiries/test.json.zip")

In [4]:
#データの確認
print(train.shape)
display(train.head())
print(test.shape)
display(test.head())

(49352, 15)

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,manager_id,photos,price,street_address,interest_level
4,1.0,1,8579a0b0d54db803821a35a4a615e97a,2016-06-16 05:55:27,Spacious 1 Bedroom 1 Bathroom in Williamsburg!...,145 Borinquen Place,"[Dining Room, Pre-War, Laundry in Building, Di...",40.7108,7170325,-73.9539,a10db4590843d78c784171a107bdacb4,[https://photos.renthop.com/2/7170325_3bb5ac84...,2400,145 Borinquen Place,medium
6,1.0,2,b8e75fc949a6cd8225b455648a951712,2016-06-01 05:44:33,BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...,East 44th,"[Doorman, Elevator, Laundry in Building, Dishw...",40.7513,7092344,-73.9722,955db33477af4f40004820b4aed804a0,[https://photos.renthop.com/2/7092344_7663c19a...,3800,230 East 44th,low
9,1.0,2,cd759a988b8f23924b5a2058d5ab2b49,2016-06-14 15:19:59,**FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...,East 56th Street,"[Doorman, Elevator, Laundry in Building, Laund...",40.7575,7158677,-73.9625,c8b10a317b766204f08e613cef4ce7a0,[https://photos.renthop.com/2/7158677_c897a134...,3495,405 East 56th Street,medium
10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,2016-06-24 07:54:24,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,[https://photos.renthop.com/2/7211212_1ed4542e...,3000,792 Metropolitan Avenue,medium
15,1.0,0,bfb9405149bfff42a92980b594c28234,2016-06-28 03:50:23,Over-sized Studio w abundant closets. Availabl...,East 34th Street,"[Doorman, Elevator, Fitness Center, Laundry in...",40.7439,7225292,-73.9743,2c3b41f588fbb5234d8a1e885a436cfa,[https://photos.renthop.com/2/7225292_901f1984...,2795,340 East 34th Street,low

(74659, 14)

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,manager_id,photos,price,street_address
0,1.0,1,79780be1514f645d7e6be99a3de696c5,2016-06-11 05:29:41,Large with awesome terrace--accessible via bed...,Suffolk Street,"[Elevator, Laundry in Building, Laundry in Uni...",40.7185,7142618,-73.9865,b1b1852c416d78d7765d746cb1b8921f,[https://photos.renthop.com/2/7142618_1c45a2c8...,2950,99 Suffolk Street
1,1.0,2,0,2016-06-24 06:36:34,Prime Soho - between Bleecker and Houston - Ne...,Thompson Street,"[Pre-War, Dogs Allowed, Cats Allowed]",40.7278,7210040,-74.0000,d0b5648017832b2427eeb9956d966a14,[https://photos.renthop.com/2/7210040_d824cc71...,2850,176 Thompson Street
2,1.0,0,0,2016-06-17 01:23:39,Spacious studio in Prime Location. Cleanbuildi...,Sullivan Street,"[Pre-War, Dogs Allowed, Cats Allowed]",40.7260,7174566,-74.0026,e6472c7237327dd3903b3d6f6a94515a,[https://photos.renthop.com/2/7174566_ba3a35c5...,2295,115 Sullivan Street
3,1.0,2,f9c826104b91d868e69bd25746448c0c,2016-06-21 05:06:02,For immediate access call Bryan.<br /><br />Bo...,Jones Street,"[Hardwood Floors, Dogs Allowed, Cats Allowed]",40.7321,7191391,-74.0028,41735645e0f8f13993c42894023f8e58,[https://photos.renthop.com/2/7191391_8c2f2d49...,2900,23 Jones Street
5,1.0,1,81062936e12ee5fa6cd2b965698e17d5,2016-06-16 07:24:27,Beautiful TRUE 1 bedroom in a luxury building ...,Exchange Place,"[Roof Deck, Doorman, Elevator, Fitness Center,...",40.7054,7171695,-74.0095,a742cf7dd3b2627d83417bc3a1b3ec96,[https://photos.renthop.com/2/7171695_089ffee2...,3254,20 Exchange Place

In [5]:
#最低限の前処理（特徴量追加なし）
df = train.copy()

# created を datetime に変換
df["created"] = pd.to_datetime(df["created"])

# created から最低限の情報だけ抽出
df["created_year"] = df["created"].dt.year
df["created_month"] = df["created"].dt.month
df["created_day"] = df["created"].dt.day
df["created_hour"] = df["created"].dt.hour

test_df = test.copy()

test_df["created"] = pd.to_datetime(test_df["created"])
test_df["created_year"] = test_df["created"].dt.year
test_df["created_month"] = test_df["created"].dt.month
test_df["created_day"] = test_df["created"].dt.day
test_df["created_hour"] = test_df["created"].dt.hour

In [6]:
#dtype を変換する
df["building_id"] = df["building_id"].astype("category")
df["manager_id"] = df["manager_id"].astype("category")

test_df["building_id"] = test_df["building_id"].astype("category")
test_df["manager_id"] = test_df["manager_id"].astype("category")

In [7]:
#目的変数を数値に変換
target_map = {"low": 0, "medium": 1, "high": 2}
df["target"] = df["interest_level"].map(target_map)

In [8]:
#使う特徴量（本当に最低限）
features = [
    "bathrooms", "bedrooms", "latitude", "longitude", "price",
    "building_id", "manager_id",
    "created_year", "created_month", "created_day", "created_hour"
]

In [9]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

In [10]:
def train_lgb_classifier(
        input_x,
        input_y,
        input_id,
        params,
        list_nfold=[0,1,2,3,4],
        n_splits=5,
    ):
    
    # OOF（3クラスの確率）
    train_oof = np.zeros((len(input_x), 3))
    metrics = []
    imp = pd.DataFrame()

    # Stratified KFold（分類なので必須）
    cv = list(StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=123).split(input_x, input_y))

    for nfold in list_nfold:
        print("-"*20, nfold, "-"*20)

        idx_tr, idx_va = cv[nfold][0], cv[nfold][1]
        x_tr, y_tr, id_tr = input_x.loc[idx_tr, :], input_y[idx_tr], input_id.loc[idx_tr, :]
        x_va, y_va, id_va = input_x.loc[idx_va, :], input_y[idx_va], input_id.loc[idx_va, :]

        print(x_tr.shape, y_tr.shape, id_tr.shape)
        print(x_va.shape, y_va.shape, id_va.shape)

        # モデル（分類）
        model = lgb.LGBMClassifier(**params)

        model.fit(
            x_tr,
            y_tr,
            eval_set=[(x_tr, y_tr), (x_va, y_va)],
            callbacks=[
                lgb.early_stopping(stopping_rounds=50, verbose=True),
                lgb.log_evaluation(100),
            ],
        )

        # モデル保存
        fname_lgb = f"model_lgb_fold{nfold}.pickle"
        with open(fname_lgb, "wb") as f:
            pickle.dump(model, f, protocol=4)

        # 予測（train）
        y_tr_pred = model.predict_proba(x_tr)
        y_va_pred = model.predict_proba(x_va)

        # logloss（分類）
        logloss_tr = log_loss(y_tr, y_tr_pred)
        logloss_va = log_loss(y_va, y_va_pred)

        metrics.append([nfold, logloss_tr, logloss_va])

        print("[logloss] tr:{:.4f}, va:{:.4f}".format(logloss_tr, logloss_va))

        # OOF（確率）
        train_oof[idx_va] = y_va_pred

        # imp（foldごと）
        _imp = pd.DataFrame({
            "col": input_x.columns,
            "imp": model.feature_importances_,
            "nfold": nfold
        })
        imp = pd.concat([imp, _imp], axis=0)

    # --- fold loop 終了後にまとめて計算 ---
    print("-"*20, "result", "-"*20)

    metrics = np.array(metrics)
    print(metrics)

    print("[cv] logloss_tr:{:.4f}+-{:.4f}, logloss_va:{:.4f}+-{:.4f}".format(
        metrics[:,1].mean(), metrics[:,1].std(),
        metrics[:,2].mean(), metrics[:,2].std(),
    ))

    # OOF 評価
    logloss_oof = log_loss(input_y, train_oof)
    print("[oof] logloss:{:.4f}".format(logloss_oof))

    # OOF 出力
    train_oof = pd.concat([
        input_id.reset_index(drop=True),
        pd.DataFrame(train_oof, columns=["pred_low", "pred_medium", "pred_high"])
    ], axis=1)

    # imp 集計
    imp = imp.groupby("col")["imp"].agg(["mean", "std"]).reset_index(drop=False)
    imp.columns = ["col", "imp", "imp_std"]

    return train_oof, imp, metrics

In [11]:
#パラメータを設定
params = {
    "objective": "multiclass",
    "num_class": 3,
    "metric": "multi_logloss",
    "learning_rate": 0.05,
    "num_leaves": 31,
    "feature_fraction": 0.8,
    "bagging_fraction": 0.8,
    "bagging_freq": 5,
    "seed": 42,
}

In [12]:
#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 11) (39481,) (39481, 1)
(9871, 11) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003032 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5180
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 10
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.474652	valid_1's multi_logloss: 0.58541
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.474652	valid_1's multi_logloss: 0.58541
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4747, va:0.5854
-------------------- 1 --------------------
(39481, 11) (39481,) (39481, 1)
(9871, 11) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001654 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5142
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 10
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.474488	valid_1's multi_logloss: 0.588377
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.474488	valid_1's multi_logloss: 0.588377
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4745, va:0.5884
-------------------- 2 --------------------
(39482, 11) (39482,) (39482, 1)
(9870, 11) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001605 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5145
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 10
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.47534	valid_1's multi_logloss: 0.586912
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.47534	valid_1's multi_logloss: 0.586912
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4753, va:0.5869
-------------------- 3 --------------------
(39482, 11) (39482,) (39482, 1)
(9870, 11) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001632 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5126
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 10
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.475946	valid_1's multi_logloss: 0.584212
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.475946	valid_1's multi_logloss: 0.584212
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4759, va:0.5842
-------------------- 4 --------------------
(39482, 11) (39482,) (39482, 1)
(9870, 11) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001543 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5119
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 10
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.477371	valid_1's multi_logloss: 0.577944
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.477371	valid_1's multi_logloss: 0.577944
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4774, va:0.5779
-------------------- result --------------------
[[0.         0.47465192 0.58541049]
 [1.         0.47448776 0.58837732]
 [2.         0.47534043 0.58691229]
 [3.         0.47594553 0.58421222]
 [4.         0.47737052 0.57794404]]
[cv] logloss_tr:0.4756+-0.0010, logloss_va:0.5846+-0.0036
[oof] logloss:0.5846

In [13]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)[:10]

              col     imp    imp_std
9      manager_id  3094.0  18.069311
2     building_id  2124.6  28.745434
10          price  1351.4  22.142719
1        bedrooms   553.8  10.281051
7        latitude   520.6  36.800815
8       longitude   483.8  17.838161
4    created_hour   407.6  14.656057
3     created_day   247.4  12.461942
0       bathrooms   139.8  11.077003
5   created_month    77.0  15.668440

In [14]:
#manager_id の OOF target encoding（3クラス）完全テンプレ
from sklearn.model_selection import KFold
import numpy as np
import pandas as pd

def target_encoding_oof(df, test_df, col, target_col="interest_level", n_splits=5, seed=42):
    """
    df: train 由来（target あり、前処理済み）
    test_df: test 由来（target なし、df と同じ前処理済み）
    col: "manager_id" などのカテゴリ列
    target_col: "interest_level"（high/medium/low）
    """

    # 出力用（high, medium, low の3列）
    oof_te = np.zeros((len(df), 3))
    test_te = np.zeros((len(test_df), 3))

    kf = KFold(n_splits=n_splits, shuffle=True, random_state=seed)

    for tr_idx, va_idx in kf.split(df):
        tr_x = df.iloc[tr_idx]
        va_x = df.iloc[va_idx]

        # ★ FutureWarning 対策：observed=False を明示
        stats = (
            tr_x.groupby(col, observed=False)[target_col]
            .value_counts(normalize=True)
            .unstack()
            .fillna(0)
        )

        # validation に適用
        oof_te[va_idx] = stats.reindex(va_x[col]).fillna(0).values

    # test 用（train 全体で学習）
    full_stats = (
        df.groupby(col, observed=False)[target_col]
        .value_counts(normalize=True)
        .unstack()
        .fillna(0)
    )
    test_te = full_stats.reindex(test_df[col]).fillna(0).values

    # DataFrame 化
    te_cols = [f"{col}_te_high", f"{col}_te_medium", f"{col}_te_low"]
    df_te = pd.DataFrame(oof_te, columns=te_cols, index=df.index)
    test_te = pd.DataFrame(test_te, columns=te_cols, index=test_df.index)

    return df_te, test_te

In [15]:
#manager_id の OOF target encoding
# --- ① 古い TE 列を削除（重要） ---
for c in ["manager_id_te_high", "manager_id_te_medium", "manager_id_te_low"]:
    if c in df.columns:
        df = df.drop(columns=[c])
    if c in test_df.columns:
        test_df = test_df.drop(columns=[c])

# --- ② OOF target encoding を実行 ---
df_te, test_te = target_encoding_oof(df, test_df, col="manager_id", target_col="interest_level")

# --- ③ df に TE を追加（この時点で重複なし） ---
df = pd.concat([df, df_te], axis=1)
test_df = pd.concat([test_df, test_te], axis=1)

# --- ④ 念のため重複列を削除（保険） ---
df = df.loc[:, ~df.columns.duplicated()]
test_df = test_df.loc[:, ~test_df.columns.duplicated()]

# --- ⑤ features に TE 列を追加（重複は dict で除去） ---
features += ["manager_id_te_high", "manager_id_te_medium", "manager_id_te_low"]
features = list(dict.fromkeys(features))

In [16]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

In [17]:
#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 14) (39481,) (39481, 1)
(9871, 14) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002143 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5937
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 13
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.46362	valid_1's multi_logloss: 0.577192
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.46362	valid_1's multi_logloss: 0.577192
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4636, va:0.5772
-------------------- 1 --------------------
(39481, 14) (39481,) (39481, 1)
(9871, 14) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002403 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5902
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 13
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.463024	valid_1's multi_logloss: 0.583681
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.463024	valid_1's multi_logloss: 0.583681
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4630, va:0.5837
-------------------- 2 --------------------
(39482, 14) (39482,) (39482, 1)
(9870, 14) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002553 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5903
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 13
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.463611	valid_1's multi_logloss: 0.580885
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.463611	valid_1's multi_logloss: 0.580885
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4636, va:0.5809
-------------------- 3 --------------------
(39482, 14) (39482,) (39482, 1)
(9870, 14) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002176 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5885
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 13
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.464535	valid_1's multi_logloss: 0.573534
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.464535	valid_1's multi_logloss: 0.573534
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4645, va:0.5735
-------------------- 4 --------------------
(39482, 14) (39482,) (39482, 1)
(9870, 14) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002280 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5880
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 13
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.466392	valid_1's multi_logloss: 0.571265
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.466392	valid_1's multi_logloss: 0.571265
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4664, va:0.5713
-------------------- result --------------------
[[0.         0.46361979 0.57719183]
 [1.         0.46302416 0.58368075]
 [2.         0.46361127 0.58088495]
 [3.         0.46453538 0.57353413]
 [4.         0.46639192 0.57126479]]
[cv] logloss_tr:0.4642+-0.0012, logloss_va:0.5773+-0.0046
[oof] logloss:0.5773

In [18]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)[:10]

                     col     imp    imp_std
9             manager_id  2630.6  33.760924
2            building_id  1958.4  22.131426
13                 price  1284.2  20.535335
1               bedrooms   513.6   7.469940
11     manager_id_te_low   451.6  26.829089
10    manager_id_te_high   449.2  15.023315
12  manager_id_te_medium   388.8  25.083859
8              longitude   380.0  11.895377
7               latitude   366.2  20.376457
4           created_hour   282.0  15.083103

In [19]:
#building_id OOF target encoding
# --- 古い building_id TE 列を削除 ---
for c in ["building_id_te_high", "building_id_te_medium", "building_id_te_low"]:
    if c in df.columns:
        df = df.drop(columns=[c])
    if c in test_df.columns:
        test_df = test_df.drop(columns=[c])

# --- building_id の OOF target encoding（← これが “定義” に相当） ---
df_te_b, test_te_b = target_encoding_oof(
    df, test_df,
    col="building_id",
    target_col="interest_level"
)

# --- df/test_df に TE を追加 ---
df = pd.concat([df, df_te_b], axis=1)
test_df = pd.concat([test_df, test_te_b], axis=1)

# --- 念のため重複列を削除 ---
df = df.loc[:, ~df.columns.duplicated()]
test_df = test_df.loc[:, ~test_df.columns.duplicated()]

# --- features に building_id TE を追加 ---
features += ["building_id_te_high", "building_id_te_medium", "building_id_te_low"]
features = list(dict.fromkeys(features))

In [20]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

In [21]:
#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 17) (39481,) (39481, 1)
(9871, 17) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002650 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6674
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 16
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.456672	valid_1's multi_logloss: 0.57742
Did not meet early stopping. Best iteration is:
[98]	training's multi_logloss: 0.458429	valid_1's multi_logloss: 0.577165
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4584, va:0.5772
-------------------- 1 --------------------
(39481, 17) (39481,) (39481, 1)
(9871, 17) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003128 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6633
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 16
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.455392	valid_1's multi_logloss: 0.583186
Did not meet early stopping. Best iteration is:
[99]	training's multi_logloss: 0.456256	valid_1's multi_logloss: 0.583029
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4563, va:0.5830
-------------------- 2 --------------------
(39482, 17) (39482,) (39482, 1)
(9870, 17) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003335 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6633
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 16
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.457246	valid_1's multi_logloss: 0.581911
Did not meet early stopping. Best iteration is:
[99]	training's multi_logloss: 0.458106	valid_1's multi_logloss: 0.581885
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4581, va:0.5819
-------------------- 3 --------------------
(39482, 17) (39482,) (39482, 1)
(9870, 17) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003411 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6611
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 16
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.45586	valid_1's multi_logloss: 0.574112
Did not meet early stopping. Best iteration is:
[99]	training's multi_logloss: 0.456893	valid_1's multi_logloss: 0.574076
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4569, va:0.5741
-------------------- 4 --------------------
(39482, 17) (39482,) (39482, 1)
(9870, 17) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002930 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6612
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 16
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.457461	valid_1's multi_logloss: 0.572248
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.457461	valid_1's multi_logloss: 0.572248
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4575, va:0.5722
-------------------- result --------------------
[[0.         0.45842882 0.57716454]
 [1.         0.45625572 0.58302948]
 [2.         0.45810607 0.58188453]
 [3.         0.45689259 0.57407617]
 [4.         0.45746065 0.57224832]]
[cv] logloss_tr:0.4574+-0.0008, logloss_va:0.5777+-0.0042
[oof] logloss:0.5777

In [22]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)[:10]

                      col     imp    imp_std
12             manager_id  2737.0  53.558379
2             building_id  1720.4  25.618353
16                  price  1061.6  23.447814
13     manager_id_te_high   408.8  25.312052
1                bedrooms   393.0   8.831761
14      manager_id_te_low   363.6  15.646086
3     building_id_te_high   347.8  13.461055
15   manager_id_te_medium   330.0   8.717798
11              longitude   307.0  15.763883
5   building_id_te_medium   290.8   9.602083

In [23]:
#manager_id_count / building_id_count
# --- count の辞書を作成 ---
manager_count = df["manager_id"].value_counts()
building_count = df["building_id"].value_counts()

# --- df に追加 ---
df["manager_id_count"] = df["manager_id"].map(manager_count)
df["building_id_count"] = df["building_id"].map(building_count)

# --- test_df に追加（未知IDは0） ---
test_df["manager_id_count"] = test_df["manager_id"].map(manager_count).fillna(0)
test_df["building_id_count"] = test_df["building_id"].map(building_count).fillna(0)

# --- features に追加 ---
features += ["manager_id_count", "building_id_count"]
features = list(dict.fromkeys(features))

In [24]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 19) (39481,) (39481, 1)
(9871, 19) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003226 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6942
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 18
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.457319	valid_1's multi_logloss: 0.576279
Did not meet early stopping. Best iteration is:
[97]	training's multi_logloss: 0.460124	valid_1's multi_logloss: 0.576242
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4601, va:0.5762
-------------------- 1 --------------------
(39481, 19) (39481,) (39481, 1)
(9871, 19) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003358 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6901
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 18
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.456299	valid_1's multi_logloss: 0.583301
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.456299	valid_1's multi_logloss: 0.583301
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4563, va:0.5833
-------------------- 2 --------------------
(39482, 19) (39482,) (39482, 1)
(9870, 19) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003197 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6901
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 18
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.456918	valid_1's multi_logloss: 0.580773
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.456918	valid_1's multi_logloss: 0.580773
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4569, va:0.5808
-------------------- 3 --------------------
(39482, 19) (39482,) (39482, 1)
(9870, 19) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003059 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6879
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 18
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.45661	valid_1's multi_logloss: 0.574032
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.45661	valid_1's multi_logloss: 0.574032
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4566, va:0.5740
-------------------- 4 --------------------
(39482, 19) (39482,) (39482, 1)
(9870, 19) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003137 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6880
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 18
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.45775	valid_1's multi_logloss: 0.572822
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.45775	valid_1's multi_logloss: 0.572822
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4577, va:0.5728
-------------------- result --------------------
[[0.         0.46012403 0.57624212]
 [1.         0.45629861 0.58330096]
 [2.         0.45691754 0.58077266]
 [3.         0.45660959 0.57403153]
 [4.         0.45774965 0.57282244]]
[cv] logloss_tr:0.4575+-0.0014, logloss_va:0.5774+-0.0040
[oof] logloss:0.5774

In [25]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)[:15]

                      col     imp    imp_std
13             manager_id  2487.4  53.789404
2             building_id  1718.4  37.832526
18                  price  1058.8  18.130085
15     manager_id_te_high   391.8  11.819475
1                bedrooms   390.4  14.010710
16      manager_id_te_low   337.0  22.461077
4     building_id_te_high   333.8  16.709279
17   manager_id_te_medium   324.2   8.555700
12              longitude   297.0   9.380832
6   building_id_te_medium   261.0  10.511898
5      building_id_te_low   247.8   7.328028
11               latitude   234.6   9.235800
14       manager_id_count   229.0   9.380832
3       building_id_count   226.6  13.867228
8            created_hour   224.2  15.974980

In [26]:
#photos（写真枚数）
df["num_photos"] = df["photos"].apply(len)
test_df["num_photos"] = test_df["photos"].apply(len)

features += ["num_photos"]
features = list(dict.fromkeys(features))

#features（amenities の数）
df["num_features"] = df["features"].apply(len)
test_df["num_features"] = test_df["features"].apply(len)

features += ["num_features"]
features = list(dict.fromkeys(features))

#description（説明文の長さ）
#文字数
df["description_length"] = df["description"].apply(lambda x: len(str(x)))
test_df["description_length"] = test_df["description"].apply(lambda x: len(str(x)))

#単語数
df["description_word_count"] = df["description"].apply(lambda x: len(str(x).split()))
test_df["description_word_count"] = test_df["description"].apply(lambda x: len(str(x).split()))

features += ["description_length", "description_word_count"]
features = list(dict.fromkeys(features))

In [27]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 23) (39481,) (39481, 1)
(9871, 23) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004433 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7519
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 22
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.450181	valid_1's multi_logloss: 0.572668
Did not meet early stopping. Best iteration is:
[98]	training's multi_logloss: 0.452287	valid_1's multi_logloss: 0.572417
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4523, va:0.5724
-------------------- 1 --------------------
(39481, 23) (39481,) (39481, 1)
(9871, 23) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004261 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7480
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 22
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.449149	valid_1's multi_logloss: 0.579248
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.449149	valid_1's multi_logloss: 0.579248
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4491, va:0.5792
-------------------- 2 --------------------
(39482, 23) (39482,) (39482, 1)
(9870, 23) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004032 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7479
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 22
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.449611	valid_1's multi_logloss: 0.57669
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.449611	valid_1's multi_logloss: 0.57669
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4496, va:0.5767
-------------------- 3 --------------------
(39482, 23) (39482,) (39482, 1)
(9870, 23) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004630 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7456
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 22
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.450157	valid_1's multi_logloss: 0.569931
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.450157	valid_1's multi_logloss: 0.569931
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4502, va:0.5699
-------------------- 4 --------------------
(39482, 23) (39482,) (39482, 1)
(9870, 23) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004017 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7458
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 22
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.450498	valid_1's multi_logloss: 0.568286
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.450498	valid_1's multi_logloss: 0.568286
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4505, va:0.5683
-------------------- result --------------------
[[0.         0.4522869  0.57241661]
 [1.         0.44914884 0.57924818]
 [2.         0.44961132 0.57669031]
 [3.         0.45015737 0.56993113]
 [4.         0.45049782 0.56828605]]
[cv] logloss_tr:0.4503+-0.0011, logloss_va:0.5733+-0.0041
[oof] logloss:0.5733

In [28]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)[:20]

                       col     imp    imp_std
15              manager_id  2668.0  39.477842
2              building_id  1714.0  37.795502
22                   price  1001.0  31.503968
17      manager_id_te_high   366.6  11.480418
1                 bedrooms   366.4  10.502381
4      building_id_te_high   283.6  19.641792
18       manager_id_te_low   278.4  11.502174
19    manager_id_te_medium   270.2  14.463748
14               longitude   253.8  15.122830
6    building_id_te_medium   226.8  12.969194
16        manager_id_count   194.8  17.810109
13                latitude   187.2   8.467585
5       building_id_te_low   186.0  13.000000
3        building_id_count   177.4  10.784248
8             created_hour   167.4  13.939153
21              num_photos   160.2   5.630275
20            num_features   153.2  15.188812
12  description_word_count    99.6   6.730527
11      description_length    71.6  14.758049
7              created_day    69.6   2.302173

In [29]:
#price_log（log1p）を追加
df["price_log"] = np.log1p(df["price"])
test_df["price_log"] = np.log1p(test_df["price"])

features += ["price_log"]
features = list(dict.fromkeys(features))

In [30]:
#created_time の強化
df["created_weekday"] = df["created"].dt.weekday
df["created_weekofyear"] = df["created"].dt.isocalendar().week.astype(int)
df["created_is_weekend"] = (df["created_weekday"] >= 5).astype(int)

test_df["created_weekday"] = test_df["created"].dt.weekday
test_df["created_weekofyear"] = test_df["created"].dt.isocalendar().week.astype(int)
test_df["created_is_weekend"] = (test_df["created_weekday"] >= 5).astype(int)

features += ["created_weekday", "created_weekofyear", "created_is_weekend"]
features = list(dict.fromkeys(features))

In [31]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 27) (39481,) (39481, 1)
(9871, 27) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005132 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7798
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 26
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.449507	valid_1's multi_logloss: 0.571265
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.449507	valid_1's multi_logloss: 0.571265
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4495, va:0.5713
-------------------- 1 --------------------
(39481, 27) (39481,) (39481, 1)
(9871, 27) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004909 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7759
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 26
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.448827	valid_1's multi_logloss: 0.578382
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.448827	valid_1's multi_logloss: 0.578382
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4488, va:0.5784
-------------------- 2 --------------------
(39482, 27) (39482,) (39482, 1)
(9870, 27) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004847 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7758
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 26
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.450463	valid_1's multi_logloss: 0.57667
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.450463	valid_1's multi_logloss: 0.57667
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4505, va:0.5767
-------------------- 3 --------------------
(39482, 27) (39482,) (39482, 1)
(9870, 27) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008591 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7735
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 26
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.450133	valid_1's multi_logloss: 0.569125
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.450133	valid_1's multi_logloss: 0.569125
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4501, va:0.5691
-------------------- 4 --------------------
(39482, 27) (39482,) (39482, 1)
(9870, 27) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005078 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7737
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 26
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.451955	valid_1's multi_logloss: 0.567438
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.451955	valid_1's multi_logloss: 0.567438
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4520, va:0.5674
-------------------- result --------------------
[[0.         0.4495072  0.57126535]
 [1.         0.44882715 0.5783817 ]
 [2.         0.45046337 0.57666978]
 [3.         0.45013273 0.56912462]
 [4.         0.451955   0.56743836]]
[cv] logloss_tr:0.4502+-0.0011, logloss_va:0.5726+-0.0043
[oof] logloss:0.5726

In [32]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)

                       col     imp    imp_std
18              manager_id  2521.0   8.916277
2              building_id  1701.2  16.146207
25                   price  1004.2  18.417383
1                 bedrooms   391.2   9.731393
20      manager_id_te_high   326.0   4.358899
21       manager_id_te_low   284.2  18.593009
22    manager_id_te_medium   276.0   6.244998
4      building_id_te_high   273.8  10.353743
17               longitude   257.8  12.814055
6    building_id_te_medium   209.4   7.987490
16                latitude   199.8   7.563068
8             created_hour   185.6  23.276598
19        manager_id_count   182.6  15.208550
5       building_id_te_low   176.8  14.822281
3        building_id_count   170.8  10.986355
26               price_log   163.8   9.959920
24              num_photos   156.8   8.927486
23            num_features   152.4   7.127412
15  description_word_count   113.0  10.793517
14      description_length    69.2  20.571825
12      created_weekofyear    63.4  12.601587
7              created_day    61.4  10.922454
0                bathrooms    28.2   4.324350
11         created_weekday    21.4   6.107373
10           created_month     9.8   5.974948
9       created_is_weekend     0.2   0.447214
13            created_year     0.0   0.000000

In [33]:
#price_per_bedroom（価格の正規化）
df["price_per_bedroom"] = df["price"] / (df["bedrooms"] + 1)
test_df["price_per_bedroom"] = test_df["price"] / (test_df["bedrooms"] + 1)

features += ["price_per_bedroom"]
features = list(dict.fromkeys(features))

In [34]:
#manager_id × building_id の交互作用（count）
df["manager_building"] = df["manager_id"].astype(str) + "_" + df["building_id"].astype(str)
test_df["manager_building"] = test_df["manager_id"].astype(str) + "_" + test_df["building_id"].astype(str)

# train + test の結合で count を作る
all_mb = pd.concat([df["manager_building"], test_df["manager_building"]])

mb_count = all_mb.value_counts()

df["manager_building_count"] = df["manager_building"].map(mb_count)
test_df["manager_building_count"] = test_df["manager_building"].map(mb_count)

features += ["manager_building_count"]
features = list(dict.fromkeys(features))

In [35]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 29) (39481,) (39481, 1)
(9871, 29) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006622 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8153
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 28
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.443598	valid_1's multi_logloss: 0.563578
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.443598	valid_1's multi_logloss: 0.563578
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4436, va:0.5636
-------------------- 1 --------------------
(39481, 29) (39481,) (39481, 1)
(9871, 29) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007927 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8114
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 28
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.442103	valid_1's multi_logloss: 0.572538
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.442103	valid_1's multi_logloss: 0.572538
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4421, va:0.5725
-------------------- 2 --------------------
(39482, 29) (39482,) (39482, 1)
(9870, 29) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005925 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8113
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 28
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.445352	valid_1's multi_logloss: 0.568787
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.445352	valid_1's multi_logloss: 0.568787
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4454, va:0.5688
-------------------- 3 --------------------
(39482, 29) (39482,) (39482, 1)
(9870, 29) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005496 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8090
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 28
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.444209	valid_1's multi_logloss: 0.561274
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.444209	valid_1's multi_logloss: 0.561274
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4442, va:0.5613
-------------------- 4 --------------------
(39482, 29) (39482,) (39482, 1)
(9870, 29) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006738 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8092
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 28
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.444951	valid_1's multi_logloss: 0.559565
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.444951	valid_1's multi_logloss: 0.559565
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4450, va:0.5596
-------------------- result --------------------
[[0.         0.44359758 0.56357826]
 [1.         0.44210251 0.57253767]
 [2.         0.44535179 0.56878686]
 [3.         0.44420881 0.56127438]
 [4.         0.44495076 0.55956489]]
[cv] logloss_tr:0.4440+-0.0011, logloss_va:0.5651+-0.0048
[oof] logloss:0.5651

In [36]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)

                       col     imp    imp_std
19              manager_id  2391.2  10.497619
2              building_id  1646.0  30.000000
26                   price   701.2  29.123873
28       price_per_bedroom   683.8  23.488295
21      manager_id_te_high   334.8  12.969194
17               longitude   289.6  14.258331
4      building_id_te_high   269.6   3.646917
23    manager_id_te_medium   264.6  16.040574
22       manager_id_te_low   251.0  17.131842
16                latitude   205.6  10.644247
6    building_id_te_medium   194.8  13.274035
27               price_log   193.8   6.260990
24            num_features   190.0  11.789826
5       building_id_te_low   189.2  15.449919
8             created_hour   184.6  14.656057
20        manager_id_count   176.8  13.553597
25              num_photos   158.8  13.217413
3        building_id_count   156.2  11.031772
15  description_word_count   103.4  10.502381
14      description_length    88.0  10.271319
1                 bedrooms    84.8   6.942622
12      created_weekofyear    65.0  10.440307
18  manager_building_count    62.8   9.576012
7              created_day    53.4   4.159327
0                bathrooms    31.6   4.979960
11         created_weekday    18.2   7.049823
10           created_month    10.4   5.029911
9       created_is_weekend     0.8   0.836660
13            created_year     0.0   0.000000

In [37]:
#description 軽量 TF‑IDF（20〜50 次元）テンプレ
#1. TF‑IDF を学習して次元圧縮（SVD）する
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

# ① TF-IDF（語彙数を制限して軽量化）
tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=5000,   # 語彙数を制限（軽量化）
)

tfidf_train = tfidf.fit_transform(df["description"])
tfidf_test  = tfidf.transform(test_df["description"])

# ② SVD で次元圧縮（20〜50 次元がベスト）今回は30
svd = TruncatedSVD(n_components=30, random_state=42)

svd_train = svd.fit_transform(tfidf_train)
svd_test  = svd.transform(tfidf_test)

In [38]:
#2. 圧縮後の TF‑IDF を df に追加する
# 30 次元の TF-IDF を特徴量として追加
for i in range(30):
    df[f"tfidf_{i}"] = svd_train[:, i]
    test_df[f"tfidf_{i}"] = svd_test[:, i]

In [39]:
#3. features に追加する（重複排除つき）
features += [f"tfidf_{i}" for i in range(30)]
features = list(dict.fromkeys(features))

In [40]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 59) (39481,) (39481, 1)
(9871, 59) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010836 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15803
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 58
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.439796	valid_1's multi_logloss: 0.564899
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.439796	valid_1's multi_logloss: 0.564899
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4398, va:0.5649
-------------------- 1 --------------------
(39481, 59) (39481,) (39481, 1)
(9871, 59) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010834 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15764
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 58
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.438918	valid_1's multi_logloss: 0.574423
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.438918	valid_1's multi_logloss: 0.574423
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4389, va:0.5744
-------------------- 2 --------------------
(39482, 59) (39482,) (39482, 1)
(9870, 59) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012127 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15763
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 58
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.440294	valid_1's multi_logloss: 0.572083
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.440294	valid_1's multi_logloss: 0.572083
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4403, va:0.5721
-------------------- 3 --------------------
(39482, 59) (39482,) (39482, 1)
(9870, 59) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010836 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 58
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.439854	valid_1's multi_logloss: 0.564131
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.439854	valid_1's multi_logloss: 0.564131
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4399, va:0.5641
-------------------- 4 --------------------
(39482, 59) (39482,) (39482, 1)
(9870, 59) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010682 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15742
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 58
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.441092	valid_1's multi_logloss: 0.561663
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.441092	valid_1's multi_logloss: 0.561663
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4411, va:0.5617
-------------------- result --------------------
[[0.         0.43979626 0.56489861]
 [1.         0.43891838 0.57442319]
 [2.         0.44029448 0.57208329]
 [3.         0.4398544  0.56413102]
 [4.         0.44109186 0.56166324]]
[cv] logloss_tr:0.4400+-0.0007, logloss_va:0.5674+-0.0049
[oof] logloss:0.5674

In [41]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)[:20]

                      col     imp    imp_std
19             manager_id  2409.2  21.135279
2             building_id  1655.4  21.812840
26                  price   648.4  21.431286
28      price_per_bedroom   632.0  14.456832
21     manager_id_te_high   266.2   7.155418
17              longitude   247.8   8.955445
4     building_id_te_high   240.2   1.483240
22      manager_id_te_low   237.6  11.802542
23   manager_id_te_medium   212.8   7.854935
6   building_id_te_medium   173.6   2.701851
24           num_features   148.8  17.224982
8            created_hour   146.0  17.073371
16               latitude   145.4  12.198361
20       manager_id_count   125.4  13.575714
3       building_id_count   124.8  13.386560
25             num_photos   119.6  10.285913
5      building_id_te_low   119.2  13.516656
27              price_log   102.6   3.361547
29                tfidf_0    62.4  11.349009
1                bedrooms    59.8   5.310367

In [42]:
# 旧SVD 30軸を削除
for i in range(30):
    col = f"tfidf_{i}"
    if col in df.columns:
        df.drop(columns=[col], inplace=True)
        test_df.drop(columns=[col], inplace=True)

In [43]:
# features から古い30軸を削除
for i in range(30):
    col = f"tfidf_{i}"
    if col in features:
        features.remove(col)

In [44]:
# ============================
# 1. TF-IDF（3000語に縮小）
# ============================
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=3000,
    stop_words='english'
)

tfidf_train = tfidf.fit_transform(df["description"])
tfidf_test = tfidf.transform(test_df["description"])


# ============================
# 2. SVD（20次元に圧縮）
# ============================
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(
    n_components=20,
    random_state=42
)

svd_train = svd.fit_transform(tfidf_train)
svd_test = svd.transform(tfidf_test)


# ============================
# 3. df に 20 個の意味軸を追加
# ============================
for i in range(20):
    df[f"tfidf_{i}"] = svd_train[:, i]
    test_df[f"tfidf_{i}"] = svd_test[:, i]


# ============================
# 4. features に追加（あなたは手動管理型なので必要）
# ============================
features += [f"tfidf_{i}" for i in range(20)]
features = list(dict.fromkeys(features))  # 重複排除

In [45]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 49) (39481,) (39481, 1)
(9871, 49) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009838 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13253
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 48
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.441661	valid_1's multi_logloss: 0.564942
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.441661	valid_1's multi_logloss: 0.564942
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4417, va:0.5649
-------------------- 1 --------------------
(39481, 49) (39481,) (39481, 1)
(9871, 49) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009371 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13214
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 48
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.439407	valid_1's multi_logloss: 0.57314
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.439407	valid_1's multi_logloss: 0.57314
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4394, va:0.5731
-------------------- 2 --------------------
(39482, 49) (39482,) (39482, 1)
(9870, 49) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009388 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13213
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 48
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.441643	valid_1's multi_logloss: 0.570966
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.441643	valid_1's multi_logloss: 0.570966
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4416, va:0.5710
-------------------- 3 --------------------
(39482, 49) (39482,) (39482, 1)
(9870, 49) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009654 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13190
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 48
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.441306	valid_1's multi_logloss: 0.563404
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.441306	valid_1's multi_logloss: 0.563404
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4413, va:0.5634
-------------------- 4 --------------------
(39482, 49) (39482,) (39482, 1)
(9870, 49) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008994 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13192
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 48
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.442274	valid_1's multi_logloss: 0.561337
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.442274	valid_1's multi_logloss: 0.561337
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4423, va:0.5613
-------------------- result --------------------
[[0.         0.44166138 0.56494193]
 [1.         0.43940662 0.57314002]
 [2.         0.44164294 0.57096599]
 [3.         0.44130552 0.56340383]
 [4.         0.44227428 0.56133708]]
[cv] logloss_tr:0.4413+-0.0010, logloss_va:0.5668+-0.0045
[oof] logloss:0.5668

In [46]:
# ============================
# 古い tfidf_0〜tfidf_19 を削除
# ============================
for i in range(20):
    col = f"tfidf_{i}"
    if col in df.columns:
        df.drop(columns=[col], inplace=True)
    if col in test_df.columns:
        test_df.drop(columns=[col], inplace=True)
    if col in features:
        features.remove(col)


# ============================
# TF-IDF（2000語）
# ============================
tfidf = TfidfVectorizer(
    max_features=2000,
    stop_words='english'
)

tfidf_train = tfidf.fit_transform(df["description"])
tfidf_test = tfidf.transform(test_df["description"])


# ============================
# SVD（10軸）
# ============================
svd = TruncatedSVD(
    n_components=10,
    random_state=42
)

svd_train = svd.fit_transform(tfidf_train)
svd_test = svd.transform(tfidf_test)


# ============================
# df に追加
# ============================
for i in range(10):
    df[f"tfidf_{i}"] = svd_train[:, i]
    test_df[f"tfidf_{i}"] = svd_test[:, i]


# ============================
# features に追加（あなたは手動管理型）
# ============================
features += [f"tfidf_{i}" for i in range(10)]
features = list(dict.fromkeys(features))

In [47]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 39) (39481,) (39481, 1)
(9871, 39) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007831 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10703
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 38
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.441395	valid_1's multi_logloss: 0.566241
Did not meet early stopping. Best iteration is:
[93]	training's multi_logloss: 0.449094	valid_1's multi_logloss: 0.566209
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4491, va:0.5662
-------------------- 1 --------------------
(39481, 39) (39481,) (39481, 1)
(9871, 39) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007087 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10664
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 38
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.439858	valid_1's multi_logloss: 0.573914
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.439858	valid_1's multi_logloss: 0.573914
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4399, va:0.5739
-------------------- 2 --------------------
(39482, 39) (39482,) (39482, 1)
(9870, 39) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007700 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10663
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 38
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.442821	valid_1's multi_logloss: 0.571254
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.442821	valid_1's multi_logloss: 0.571254
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4428, va:0.5713
-------------------- 3 --------------------
(39482, 39) (39482,) (39482, 1)
(9870, 39) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007663 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10640
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 38
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.441308	valid_1's multi_logloss: 0.561803
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.441308	valid_1's multi_logloss: 0.561803
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4413, va:0.5618
-------------------- 4 --------------------
(39482, 39) (39482,) (39482, 1)
(9870, 39) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007634 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10642
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 38
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.441858	valid_1's multi_logloss: 0.561627
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.441858	valid_1's multi_logloss: 0.561627
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4419, va:0.5616
-------------------- result --------------------
[[0.         0.44909375 0.56620852]
 [1.         0.43985808 0.57391352]
 [2.         0.44282065 0.57125433]
 [3.         0.44130844 0.5618029 ]
 [4.         0.44185774 0.56162711]]
[cv] logloss_tr:0.4430+-0.0032, logloss_va:0.5670+-0.0049
[oof] logloss:0.5670

In [48]:
# ============================
# description の SVD を完全削除
# ============================

# 旧SVDの列名（tfidf_0〜tfidf_29 など）を全て削除
for i in range(50):  # 念のため最大50まで
    col = f"tfidf_{i}"
    
    # df から削除
    if col in df.columns:
        df.drop(columns=[col], inplace=True)
    
    # test_df から削除
    if col in test_df.columns:
        test_df.drop(columns=[col], inplace=True)
    
    # features から削除
    if col in features:
        features.remove(col)

In [49]:
#Step 1：アメニティ（features）を文字列に変換
#amenities（features）TF‑IDF → SVD（20軸）
# features（アメニティ）をスペース区切りの文字列に変換
df["amenities_text"] = df["features"].apply(lambda x: " ".join(x) if isinstance(x, list) else "")
test_df["amenities_text"] = test_df["features"].apply(lambda x: " ".join(x) if isinstance(x, list) else "")

In [50]:
#Step 2：TF‑IDF（2000語）
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_amen = TfidfVectorizer(
    max_features=2000,
    stop_words='english'
)

tfidf_train_amen = tfidf_amen.fit_transform(df["amenities_text"])
tfidf_test_amen = tfidf_amen.transform(test_df["amenities_text"])

In [51]:
#Step 3：SVD（20軸）
from sklearn.decomposition import TruncatedSVD

svd_amen = TruncatedSVD(
    n_components=20,
    random_state=42
)

svd_train_amen = svd_amen.fit_transform(tfidf_train_amen)
svd_test_amen = svd_amen.transform(tfidf_test_amen)

In [52]:
#Step 4：df / test_df に追加
for i in range(20):
    df[f"amen_svd_{i}"] = svd_train_amen[:, i]
    test_df[f"amen_svd_{i}"] = svd_test_amen[:, i]

In [53]:
#Step 5：features に追加
features += [f"amen_svd_{i}" for i in range(20)]
features = list(dict.fromkeys(features))  # 重複排除

In [54]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 49) (39481,) (39481, 1)
(9871, 49) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010019 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13244
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 48
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.439086	valid_1's multi_logloss: 0.560675
Did not meet early stopping. Best iteration is:
[99]	training's multi_logloss: 0.440231	valid_1's multi_logloss: 0.56063
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4402, va:0.5606
-------------------- 1 --------------------
(39481, 49) (39481,) (39481, 1)
(9871, 49) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012464 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13205
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 48
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.437255	valid_1's multi_logloss: 0.570276
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.437255	valid_1's multi_logloss: 0.570276
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4373, va:0.5703
-------------------- 2 --------------------
(39482, 49) (39482,) (39482, 1)
(9870, 49) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010009 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13201
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 48
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.439727	valid_1's multi_logloss: 0.568438
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.439727	valid_1's multi_logloss: 0.568438
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4397, va:0.5684
-------------------- 3 --------------------
(39482, 49) (39482,) (39482, 1)
(9870, 49) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009107 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13181
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 48
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.438814	valid_1's multi_logloss: 0.55916
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.438814	valid_1's multi_logloss: 0.55916
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4388, va:0.5592
-------------------- 4 --------------------
(39482, 49) (39482,) (39482, 1)
(9870, 49) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010430 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13184
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 48
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.440173	valid_1's multi_logloss: 0.558321
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.440173	valid_1's multi_logloss: 0.558321
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4402, va:0.5583
-------------------- result --------------------
[[0.         0.44023086 0.56062965]
 [1.         0.43725473 0.57027569]
 [2.         0.43972704 0.56843818]
 [3.         0.43881368 0.55915988]
 [4.         0.44017282 0.55832123]]
[cv] logloss_tr:0.4392+-0.0011, logloss_va:0.5634+-0.0050
[oof] logloss:0.5634

In [55]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)[:25]

                       col     imp    imp_std
39              manager_id  2372.2  29.388773
22             building_id  1533.4  32.469986
48       price_per_bedroom   638.2   5.890671
46                   price   619.8  21.959053
37               longitude   251.0  15.795569
43    manager_id_te_medium   236.0   9.486833
41      manager_id_te_high   231.8  11.562872
24     building_id_te_high   227.6  10.830512
42       manager_id_te_low   226.6   9.396808
47               price_log   192.6   7.536577
26   building_id_te_medium   186.8   5.357238
17              amen_svd_7   168.4   6.877500
36                latitude   154.0  15.165751
25      building_id_te_low   143.0   7.176350
40        manager_id_count   132.0  11.313708
28            created_hour   127.4  12.934450
23       building_id_count   127.4   9.581232
45              num_photos   125.8   7.529940
44            num_features   123.2  12.316655
15              amen_svd_5   108.0  14.071247
16              amen_svd_6    77.6   4.560702
35  description_word_count    73.4  11.717508
14              amen_svd_4    69.0  11.683321
19              amen_svd_9    62.4   9.449868
21                bedrooms    62.0   8.154753

In [56]:
#display_address / street_address の簡易特徴
# display_address
df["display_len"] = df["display_address"].apply(lambda x: len(str(x)))
test_df["display_len"] = test_df["display_address"].apply(lambda x: len(str(x)))

df["display_words"] = df["display_address"].apply(lambda x: len(str(x).split()))
test_df["display_words"] = test_df["display_address"].apply(lambda x: len(str(x).split()))

df["display_first"] = df["display_address"].apply(lambda x: str(x).split()[0] if len(str(x).split()) > 0 else "")
test_df["display_first"] = test_df["display_address"].apply(lambda x: str(x).split()[0] if len(str(x).split()) > 0 else "")

df["display_last"] = df["display_address"].apply(lambda x: str(x).split()[-1] if len(str(x).split()) > 0 else "")
test_df["display_last"] = test_df["display_address"].apply(lambda x: str(x).split()[-1] if len(str(x).split()) > 0 else "")

# street_address
df["street_len"] = df["street_address"].apply(lambda x: len(str(x)))
test_df["street_len"] = test_df["street_address"].apply(lambda x: len(str(x)))

df["street_words"] = df["street_address"].apply(lambda x: len(str(x).split()))
test_df["street_words"] = test_df["street_address"].apply(lambda x: len(str(x).split()))

df["street_first"] = df["street_address"].apply(lambda x: str(x).split()[0] if len(str(x).split()) > 0 else "")
test_df["street_first"] = test_df["street_address"].apply(lambda x: str(x).split()[0] if len(str(x).split()) > 0 else "")

df["street_last"] = df["street_address"].apply(lambda x: str(x).split()[-1] if len(str(x).split()) > 0 else "")
test_df["street_last"] = test_df["street_address"].apply(lambda x: str(x).split()[-1] if len(str(x).split()) > 0 else "")

# features に追加
addr_cols = [
    "display_len", "display_words", "display_first", "display_last",
    "street_len", "street_words", "street_first", "street_last"
]

for col in addr_cols:
    if col not in features:
        features.append(col)

In [57]:
#display_first / display_last / street_first / street_last を Label Encoding
from sklearn.preprocessing import LabelEncoder

cat_cols = ["display_first", "display_last", "street_first", "street_last"]

for col in cat_cols:
    le = LabelEncoder()
    
    # train + test を結合して fit（未知カテゴリ対策）
    all_values = pd.concat([df[col], test_df[col]]).astype(str)
    le.fit(all_values)
    
    df[col] = le.transform(df[col].astype(str))
    test_df[col] = le.transform(test_df[col].astype(str))
    
    # features に追加
    if col not in features:
        features.append(col)

In [58]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 57) (39481,) (39481, 1)
(9871, 57) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014565 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14266
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 56
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.438818	valid_1's multi_logloss: 0.56176
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.438818	valid_1's multi_logloss: 0.56176
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4388, va:0.5618
-------------------- 1 --------------------
(39481, 57) (39481,) (39481, 1)
(9871, 57) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010966 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14236
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 56
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.436446	valid_1's multi_logloss: 0.572115
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.436446	valid_1's multi_logloss: 0.572115
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4364, va:0.5721
-------------------- 2 --------------------
(39482, 57) (39482,) (39482, 1)
(9870, 57) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003627 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14250
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 56
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.438296	valid_1's multi_logloss: 0.568002
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.438296	valid_1's multi_logloss: 0.568002
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4383, va:0.5680
-------------------- 3 --------------------
(39482, 57) (39482,) (39482, 1)
(9870, 57) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010306 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14218
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 56
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.438037	valid_1's multi_logloss: 0.559756
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.438037	valid_1's multi_logloss: 0.559756
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4380, va:0.5598
-------------------- 4 --------------------
(39482, 57) (39482,) (39482, 1)
(9870, 57) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014177 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14207
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 56
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.438865	valid_1's multi_logloss: 0.558528
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.438865	valid_1's multi_logloss: 0.558528
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4389, va:0.5585
-------------------- result --------------------
[[0.         0.43881792 0.56175998]
 [1.         0.43644587 0.5721154 ]
 [2.         0.43829586 0.56800213]
 [3.         0.43803734 0.55975595]
 [4.         0.438865   0.55852776]]
[cv] logloss_tr:0.4381+-0.0009, logloss_va:0.5640+-0.0052
[oof] logloss:0.5640

In [59]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=True)[:35]

                       col   imp    imp_std
33            created_year   0.0   0.000000
29      created_is_weekend   0.4   0.547723
56            street_words   4.2   2.280351
30           created_month   4.8   3.768289
31         created_weekday  11.4   4.929503
55              street_len  11.4   2.190890
37            display_last  15.6   3.130495
20               bathrooms  15.8   1.303840
7              amen_svd_15  22.2   8.258329
8              amen_svd_16  22.8   3.271085
13              amen_svd_3  23.0   6.892024
6              amen_svd_14  24.6   3.781534
5              amen_svd_13  26.2   5.357238
10             amen_svd_18  26.8   6.906519
18              amen_svd_8  27.2   8.555700
3              amen_svd_11  28.6   8.384510
39           display_words  28.6   3.361547
38             display_len  29.0   2.449490
11             amen_svd_19  29.2   4.549725
0               amen_svd_0  31.2   7.120393
12              amen_svd_2  31.4   3.361547
42  manager_building_count  33.0   6.041523
27             created_day  34.2   5.118594
2              amen_svd_10  34.6   4.929503
9              amen_svd_17  41.4   6.877500
32      created_weekofyear  42.0  12.903488
54             street_last  43.8   5.974948
36           display_first  45.2   6.300794
34      description_length  46.2   9.602083
1               amen_svd_1  46.4   8.264381
4              amen_svd_12  49.2   4.764452
21                bedrooms  50.4   6.107373
19              amen_svd_9  58.4   4.219005
14              amen_svd_4  63.8   9.471008
53            street_first  64.2   6.942622

In [60]:
cols_to_drop = ["display_last", "street_len", "street_words"]

# df / test_df から削除
df.drop(columns=cols_to_drop, inplace=True, errors="ignore")
test_df.drop(columns=cols_to_drop, inplace=True, errors="ignore")

# features から削除
features = [f for f in features if f not in cols_to_drop]

In [61]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 54) (39481,) (39481, 1)
(9871, 54) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010680 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14015
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 53
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.439275	valid_1's multi_logloss: 0.560965
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.439275	valid_1's multi_logloss: 0.560965
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4393, va:0.5610
-------------------- 1 --------------------
(39481, 54) (39481,) (39481, 1)
(9871, 54) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010674 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13982
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 53
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.436656	valid_1's multi_logloss: 0.570784
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.436656	valid_1's multi_logloss: 0.570784
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4367, va:0.5708
-------------------- 2 --------------------
(39482, 54) (39482,) (39482, 1)
(9870, 54) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010626 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13998
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 53
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.438412	valid_1's multi_logloss: 0.567839
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.438412	valid_1's multi_logloss: 0.567839
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4384, va:0.5678
-------------------- 3 --------------------
(39482, 54) (39482,) (39482, 1)
(9870, 54) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010170 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13972
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 53
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.438344	valid_1's multi_logloss: 0.558586
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.438344	valid_1's multi_logloss: 0.558586
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4383, va:0.5586
-------------------- 4 --------------------
(39482, 54) (39482,) (39482, 1)
(9870, 54) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010441 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13958
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 53
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.43964	valid_1's multi_logloss: 0.557835
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.43964	valid_1's multi_logloss: 0.557835
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4396, va:0.5578
-------------------- result --------------------
[[0.         0.43927463 0.56096496]
 [1.         0.43665582 0.57078446]
 [2.         0.43841167 0.56783868]
 [3.         0.43834423 0.55858633]
 [4.         0.43963957 0.55783503]]
[cv] logloss_tr:0.4385+-0.0010, logloss_va:0.5632+-0.0052
[oof] logloss:0.5632

In [62]:
#manager_building の OOF Target Encoding
#1. manager_building を作る
df["manager_building"] = df["manager_id"].astype(str) + "_" + df["building_id"].astype(str)
test_df["manager_building"] = test_df["manager_id"].astype(str) + "_" + test_df["building_id"].astype(str)

In [63]:
#2. target_encoding_oof 関数を正しく呼ぶ
df_mb_te, test_mb_te = target_encoding_oof(
    df=df,
    test_df=test_df,
    col="manager_building",
    target_col="interest_level",   # ← ここが正しい
    n_splits=5,
    seed=42
)

In [64]:
#3. df / test_df に結合
df = pd.concat([df, df_mb_te], axis=1)
test_df = pd.concat([test_df, test_mb_te], axis=1)

#重複列を削除
df = df.loc[:, ~df.columns.duplicated()]
test_df = test_df.loc[:, ~test_df.columns.duplicated()]

In [65]:
#4. features に追加
features += [
    "manager_building_te_high",
    "manager_building_te_medium",
    "manager_building_te_low"
]
features = list(dict.fromkeys(features))

In [66]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 57) (39481,) (39481, 1)
(9871, 57) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004863 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14402
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 56
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.437448	valid_1's multi_logloss: 0.560224
Did not meet early stopping. Best iteration is:
[99]	training's multi_logloss: 0.438599	valid_1's multi_logloss: 0.560186
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4386, va:0.5602
-------------------- 1 --------------------
(39481, 57) (39481,) (39481, 1)
(9871, 57) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012018 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14367
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 56
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.436031	valid_1's multi_logloss: 0.570061
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.436031	valid_1's multi_logloss: 0.570061
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4360, va:0.5701
-------------------- 2 --------------------
(39482, 57) (39482,) (39482, 1)
(9870, 57) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011517 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14393
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 56
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.437665	valid_1's multi_logloss: 0.567039
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.437665	valid_1's multi_logloss: 0.567039
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4377, va:0.5670
-------------------- 3 --------------------
(39482, 57) (39482,) (39482, 1)
(9870, 57) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012363 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14362
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 56
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.437134	valid_1's multi_logloss: 0.55857
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.437134	valid_1's multi_logloss: 0.55857
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4371, va:0.5586
-------------------- 4 --------------------
(39482, 57) (39482,) (39482, 1)
(9870, 57) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005536 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14351
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 56
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.437921	valid_1's multi_logloss: 0.557271
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.437921	valid_1's multi_logloss: 0.557271
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4379, va:0.5573
-------------------- result --------------------
[[0.         0.4385994  0.56018615]
 [1.         0.43603067 0.57006095]
 [2.         0.43766501 0.56703878]
 [3.         0.43713421 0.55857028]
 [4.         0.43792092 0.55727122]]
[cv] logloss_tr:0.4375+-0.0009, logloss_va:0.5626+-0.0050
[oof] logloss:0.5626

In [67]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)[:25]

                           col     imp    imp_std
45                  manager_id  2366.6  40.814213
22                 building_id  1498.6  24.079037
54           price_per_bedroom   629.6  16.456002
52                       price   622.8  16.589153
47          manager_id_te_high   258.2  19.279523
40                   longitude   232.2  14.149205
49        manager_id_te_medium   210.8  13.103435
24         building_id_te_high   189.4  14.275854
48           manager_id_te_low   179.6  12.340989
26       building_id_te_medium   166.4  10.644247
53                   price_log   157.2  10.568822
17                  amen_svd_7   150.0  12.041595
39                    latitude   135.8  11.454257
46            manager_id_count   129.4   8.706320
51                  num_photos   124.8   8.288546
23           building_id_count   121.0  11.575837
25          building_id_te_low   120.0  14.525839
50                num_features   115.8  14.889594
28                created_hour    98.0   7.968689
15                  amen_svd_5    95.4  15.549920
43     manager_building_te_low    83.8   8.497058
44  manager_building_te_medium    81.0   7.615773
16                  amen_svd_6    75.6   4.615192
35      description_word_count    68.4  10.358571
14                  amen_svd_4    65.8   8.467585

In [68]:
#created 系の弱い特徴を削る
cols_to_drop = [
    "created_year",
    "created_is_weekend",
    "created_month",
    "created_weekday"
]

df.drop(columns=cols_to_drop, inplace=True, errors="ignore")
test_df.drop(columns=cols_to_drop, inplace=True, errors="ignore")

features = [f for f in features if f not in cols_to_drop]

In [69]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 53) (39481,) (39481, 1)
(9871, 53) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009645 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14389
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 53
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.437396	valid_1's multi_logloss: 0.560609
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.437396	valid_1's multi_logloss: 0.560609
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4374, va:0.5606
-------------------- 1 --------------------
(39481, 53) (39481,) (39481, 1)
(9871, 53) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009796 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14354
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 53
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.436181	valid_1's multi_logloss: 0.569527
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.436181	valid_1's multi_logloss: 0.569527
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4362, va:0.5695
-------------------- 2 --------------------
(39482, 53) (39482,) (39482, 1)
(9870, 53) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009813 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14380
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 53
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.438268	valid_1's multi_logloss: 0.566531
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.438268	valid_1's multi_logloss: 0.566531
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4383, va:0.5665
-------------------- 3 --------------------
(39482, 53) (39482,) (39482, 1)
(9870, 53) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010688 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14349
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 53
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.437493	valid_1's multi_logloss: 0.5575
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.437493	valid_1's multi_logloss: 0.5575
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4375, va:0.5575
-------------------- 4 --------------------
(39482, 53) (39482,) (39482, 1)
(9870, 53) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010506 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14338
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 53
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.438692	valid_1's multi_logloss: 0.557594
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.438692	valid_1's multi_logloss: 0.557594
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4387, va:0.5576
-------------------- result --------------------
[[0.         0.43739588 0.56060874]
 [1.         0.43618135 0.56952728]
 [2.         0.43826755 0.56653092]
 [3.         0.43749263 0.55749976]
 [4.         0.43869221 0.55759378]]
[cv] logloss_tr:0.4376+-0.0009, logloss_va:0.5624+-0.0049
[oof] logloss:0.5624

In [70]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=True)[:35]

                           col   imp    imp_std
20                   bathrooms  16.4   3.646917
7                  amen_svd_15  21.4   3.646917
6                  amen_svd_14  21.6   7.503333
12                  amen_svd_2  22.4   6.465292
11                 amen_svd_19  23.2   2.683282
8                  amen_svd_16  23.2   4.816638
34               display_words  25.6   5.856620
33                 display_len  27.2   6.534524
37      manager_building_count  27.2   4.816638
5                  amen_svd_13  28.2   5.357238
13                  amen_svd_3  28.4   5.594640
18                  amen_svd_8  28.6   4.159327
10                 amen_svd_18  28.8   9.523655
0                   amen_svd_0  29.6   2.880972
3                  amen_svd_11  30.0   4.582576
9                  amen_svd_17  32.8   4.207137
2                  amen_svd_10  35.6   8.173127
52                 street_last  38.6   8.734987
29          created_weekofyear  42.2  11.388591
1                   amen_svd_1  42.6   8.203658
4                  amen_svd_12  43.0   7.516648
32               display_first  46.0  11.401754
27                 created_day  46.2   7.085196
19                  amen_svd_9  54.8  10.963576
38    manager_building_te_high  57.0   3.535534
30          description_length  57.0   7.778175
21                    bedrooms  57.8   6.534524
51                street_first  63.8   9.523655
14                  amen_svd_4  64.4  14.397917
31      description_word_count  66.6   9.316652
16                  amen_svd_6  78.0   4.301163
39     manager_building_te_low  81.6   4.774935
40  manager_building_te_medium  84.6   4.979960
15                  amen_svd_5  89.4  13.464769
28                created_hour  98.4  11.260551

In [71]:
#description_length と description_word_count の片方を削る
cols_to_drop = ["description_length"]

df.drop(columns=cols_to_drop, inplace=True, errors="ignore")
test_df.drop(columns=cols_to_drop, inplace=True, errors="ignore")

features = [f for f in features if f not in cols_to_drop]

In [72]:
#データセットの作成
input_x = df[features].reset_index(drop=True)
input_y = df["target"].reset_index(drop=True)
input_id = df[["listing_id"]].reset_index(drop=True)

#学習の実行
train_oof, imp, metrics = train_lgb_classifier(
    input_x=input_x,
    input_y=input_y,
    input_id=input_id,
    params=params,
)

-------------------- 0 --------------------
(39481, 52) (39481,) (39481, 1)
(9871, 52) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011716 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14134
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 52
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.436794	valid_1's multi_logloss: 0.560646
Did not meet early stopping. Best iteration is:
[98]	training's multi_logloss: 0.438903	valid_1's multi_logloss: 0.560577
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4389, va:0.5606
-------------------- 1 --------------------
(39481, 52) (39481,) (39481, 1)
(9871, 52) (9871,) (9871, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010417 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14099
[LightGBM] [Info] Number of data points in the train set: 39481, number of used features: 52
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364292
[LightGBM] [Info] Start training from score -1.480486
[LightGBM] [Info] Start training from score -2.553816
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.434485	valid_1's multi_logloss: 0.569639
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.434485	valid_1's multi_logloss: 0.569639
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4345, va:0.5696
-------------------- 2 --------------------
(39482, 52) (39482,) (39482, 1)
(9870, 52) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004473 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14125
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 52
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553516
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.436351	valid_1's multi_logloss: 0.566925
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.436351	valid_1's multi_logloss: 0.566925
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4364, va:0.5669
-------------------- 3 --------------------
(39482, 52) (39482,) (39482, 1)
(9870, 52) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010831 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14094
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 52
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364280
[LightGBM] [Info] Start training from score -1.480511
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.436542	valid_1's multi_logloss: 0.55851
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.436542	valid_1's multi_logloss: 0.55851
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4365, va:0.5585
-------------------- 4 --------------------
(39482, 52) (39482,) (39482, 1)
(9870, 52) (9870,) (9870, 1)
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010528 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14083
[LightGBM] [Info] Number of data points in the train set: 39482, number of used features: 52
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Start training from score -0.364317
[LightGBM] [Info] Start training from score -1.480400
[LightGBM] [Info] Start training from score -2.553842
Training until validation scores don't improve for 50 rounds
[100]	training's multi_logloss: 0.437435	valid_1's multi_logloss: 0.559193
Did not meet early stopping. Best iteration is:
[100]	training's multi_logloss: 0.437435	valid_1's multi_logloss: 0.559193
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[logloss] tr:0.4374, va:0.5592
-------------------- result --------------------
[[0.         0.43890282 0.5605769 ]
 [1.         0.43448455 0.569639  ]
 [2.         0.43635141 0.56692548]
 [3.         0.43654178 0.55850971]
 [4.         0.43743509 0.55919322]]
[cv] logloss_tr:0.4367+-0.0014, logloss_va:0.5630+-0.0045
[oof] logloss:0.5630

In [73]:
# description_length を復元
df["description_length"] = df["description"].apply(lambda x: len(str(x)))
test_df["description_length"] = test_df["description"].apply(lambda x: len(str(x)))

if "description_length" not in features:
    features.append("description_length")